server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.hxr.springcloud.entities # 所有Entity别名类所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml # mapper映射文件（通过mapper.xml文件或注释完成数据库操作）

spring:
  application:
    name: microservicecloud-dept  # 对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据库操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  # mysql驱动包
    url: jdbc:mysql://116.62.148.11:3307/cloudDB01  # 数据库名称
    username: root
    password: abc123
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间

eureka:
  #server:
  #  enable-self-preservation: false  #自我保护机制禁用
  client: #将eureka注册进eureka服务中
    service-url:
    #单机
#      defaultZone: http://localhost:7001/eureka/
    #集群
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka,http://eureka3.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix #自定义hystrix相关服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: hxr-microservicecloud
  company.name: www.hxr.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}